language: python
dist: focal
python:
  - "3.10"
before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install paramiko pyngrok Flask pytz python-telegram-bot pymongo

before_script:

  - chmod +x *
  - chmod +x Spike
  
script:
  # Run the Python script
  - python3 api.py
